clone_depth: 1

image: Visual Studio 2019

environment:
    matrix:
      - MSYSTEM: MSYS2
      - MSYSTEM: MINGW32
        ARCH: i686
      - MSYSTEM: MINGW64
        ARCH: x86_64

install:
  - ps: |
        $env:MATRIX=C:\msys64\usr\bin\bash.exe -c 'echo mingw:$ARCH:{Debug,Release}'
        $env:MAKE="mingw32-make"
  - C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
  - C:\msys64\usr\bin\bash.exe -lc "pacman -Syu --noconfirm"
  - C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm --needed mingw-w64-$ARCH-gcc mingw-w64-$ARCH-make mingw-w64-$ARCH-cmake"
      
build_script:
  - ps: |
        $env:CHERE_INVOKING="1"
        $env:GIT=C:\msys64\usr\bin\bash.exe -c '/usr/bin/which git'
  - C:\msys64\usr\bin\bash.exe -lc "$MAKE -j all"

test_script:
  - C:\msys64\usr\bin\bash.exe -lc "$MAKE -j -k test || true"
            
after_test:
  - C:\msys64\usr\bin\bash.exe -lc "$MAKE -j CLEAN=git\(gsl\)\ all\(gsl\)\ git\(pthread-win32\)\ all\(pthread-win32\) clean"

for:
  -
    matrix:
        only:
          - MSYSTEM: MSYS2

    install:
     - ps: |
           $env:MSYS2_ARG_CONV_EXCL="*"
           $env:CMAKE=C:\msys64\usr\bin\bash.exe -c '/usr/bin/which cmake'
           $env:MATRIX=C:\msys64\usr\bin\bash.exe -c 'echo msvc:{x64,Win32}:{Debug,Release}'
           $env:MAKE="make"
