language: c

matrix:
    include:
      - os: linux
        dist: xenial
        env:
          - MATRIX_EVAL='CC=gcc && CXX=g++ && ARCH="x86_64" && CFG="Debug Release"'

git:
  - depth: 1

before_install:
  - eval "$MATRIX_EVAL"

install:
  - cd ..
  - mkdir gcc
  - cd gcc
  - SRC=".." bash ../RegionsMT/.install/install_libraries.sh

script:
  - cd ../RegionsMT
  - LIBRARY_PATH="../gcc" INSTALL_PATH="../gcc" make -j