language: c

git:
    depth: 1

matrix:
    include:
      - os: linux
        dist: xenial
        env:
          - MATRIX_EVAL='MODE="linux"'
        addons:
            apt:
                packages:
                  - gcc-multilib

before_install:
  - eval "$MATRIX_EVAL"

install:
  - if [ "$MODE" == "linux" ]; then
        export TOOLCHAIN="gcc clang" ARCH="x86_64 i386" CFG="Debug Release"
        bash ../RegionsMT/.install/install_libraries.sh;
    elif [ "$MODE" == "osx" ]; then
        travis_terminate 1;
    elif [ "$MODE" == "windows" ]; then
        travis_terminate 1;
    fi

script:
  - cd ../RegionsMT
  - make -j
