language: c

git:
    depth: 1

matrix:
    include:
      - os: linux
        dist: xenial
        env:
          - MATRIX_EVAL='MODE="linux" && export CC="gcc" CXX="g++" ARCH="x86_64 i386" CFG="Debug Release"'
        addons:
            apt:
                packages:
                  - gcc-multilib

before_install:
  - eval "$MATRIX_EVAL"
  - sudo apt-get install

install:
  - cd ..
  - mkdir gcc
  - cd gcc
  - if [ $MODE == "linux" ]; then
        SRC=".." bash ../RegionsMT/.install/install_libraries.sh;
    elif [ $MODE == "osx" ]; then
        travis_terminate 1;
    elif [ $MODE == "windows" ]; then
        travis_terminate 1;
    fi

script:
  - cd ../RegionsMT
  - LIBRARY_PATH="../gcc" INSTALL_PATH="../gcc" make -j
