# <VAR>:<TOOLCHAIN>
$(call var,CC LD,gcc gcc-% clang clang-%,$$$$2)
$(call var,CXX,gcc,g++)
$(call var,CXX,gcc-%,$$$$(2:gcc-%=g++-%))
$(call var,CXX,clang clang-%,$$$$2)
$(call var,AR,gcc,gcc-ar)
$(call var,AR,gcc-%,$$$$(2:gcc-%=gcc-ar-%))
$(call var,AR,clang,llvm-ar)
$(call var,AR,clang-%,$$$$(2:clang-%=llvm-ar-%))
$(call var,RANLIB,gcc,gcc-ranlib)
$(call var,RANLIB,gcc-%,$$$$(2:gcc-%=gcc-ranlib-%))
$(call var,RANLIB,clang,llvm-ranlib)
$(call var,RANLIB,clang-%,$$$$(2:clang-%=llvm-ranlib-%))

# <VAR>:<TARGET>:<TOOLCHAIN>:<ARCH>:<CONFIG>
$(call var,CFLAGS,%,gcc gcc-% clang clang-%,%,%,-std=c11 -Wall -mavx)
$(call var,CFLAGS LDFLAGS,%,gcc gcc-% clang clang-%,i386 i686,%,-m32)
$(call var,CFLAGS LDFLAGS,%,gcc gcc-% clang clang-%,x86_64,%,-m64)
$(call var,CFLAGS LDFLAGS,%,gcc gcc-% clang clang-%,%,Release,-O3 -flto)
$(call var,CFLAGS,%,gcc gcc-% clang clang-%,%,Debug,-D_DEBUG -g)
$(call var,CFLAGS LDFLAGS,%,gcc gcc-%,%,Release,-fuse-linker-plugin)
$(call var,CFLAGS LDFLAGS,%,gcc gcc-%,%,Debug,-Og)
$(call var,CFLAGS LDFLAGS,%,clang clang-%,%,Debug,-O0)
$(call var,LDFLAGS,%,gcc gcc-% clang clang-%,%,%,-mavx)
$(call var,LDFLAGS,%,clang clang-%,%,Release,-fuse-ld=gold)
