# <VAR>:<TOOLCHAIN>
$(call var,$$$$2,,CC LD,gcc gcc-% clang clang-%)
$(call var,g++,,CXX:gcc)
$(call var,$$$$(2:gcc-%=g++-%),,CXX:gcc-%)
$(call var,$$$$2,,CXX,clang clang-%)
$(call var,gcc-ar,,AR:gcc)
$(call var,$$$$(2:gcc-%=gcc-ar-%),,AR:gcc-%)
$(call var,llvm-ar,,AR:clang)
$(call var,$$$$(2:clang-%=llvm-ar-%),,AR:clang-%)
$(call var,gcc-ranlib,,RANLIB:gcc)
$(call var,$$$$(2:gcc-%=gcc-ranlib-%),,RANLIB:gcc-%)
$(call var,llvm-ranlib,,RANLIB:clang)
$(call var,$$$$(2:clang-%=llvm-ranlib-%),,RANLIB:clang-%)

# <VAR>:<TARGET>:<TOOLCHAIN>:<ARCH>:<CONFIG>
$(call var,-std=c11 -Wall -mavx,$$1,CFLAGS:%,gcc gcc-% clang clang-%,%:%)
$(call var,-m32,CFLAGS LDFLAGS,$$1,%,gcc gcc-% clang clang-%,i386 i686,%)
$(call var,-m64,CFLAGS LDFLAGS,$$1,%,gcc gcc-% clang clang-%,x86_64:%)
$(call var,-O3 -flto,$$1,CFLAGS LDFLAGS,%,gcc gcc-% clang clang-%,%:Release)
$(call var,-D_DEBUG -g,$$1,CFLAGS:%,gcc gcc-% clang clang-%,%:Debug)
$(call var,-fuse-linker-plugin,$$1,CFLAGS LDFLAGS,%,gcc gcc-%,%:Release)
$(call var,-Og,$$1,CFLAGS LDFLAGS,%,gcc gcc-%,%:Debug)
$(call var,-O0,$$1,CFLAGS LDFLAGS,%,clang clang-%,%:Debug)
$(call var,-mavx,$$1,LDFLAGS:%,gcc gcc-% clang clang-%,%:%)
$(call var,-fuse-ld=gold,$$1,LDFLAGS:%,clang clang-%,%:Release)

$(call var,/MP /arch:AVX /volatile:ms /D_UNICODE /D_CRT_SECURE_NO_WARNINGS,$$1,CFLAGS:%:msvc:%:%)
$(call var,/MTd /Od /RTC1 /Zi /D_DEBUG,$$1,CFLAGS:%:msvc:%:Debug)
$(call var,/MT /GL /O2,$$1,CFLAGS:%:msvc:%:Release)
$(call var,/LTCG,$$1,LDFLAGS ARFLAGS,%:msvc:%:Release)

$(call var,/p:CharacterSet=Unicode,$$1,MSBUILDFLAGS:%:msvc:%:%)
$(call var,/p:WholeProgramOptimization=true,$$1,MSBUILDFLAGS:%:msvc:%:Release)
