name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
          sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main"
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y gcc-multilib clang-10 llvm-10 llvm-10-dev lld-10
    - name: setting up environment
      run: export MATRIX=`echo {clang,gcc}:{x86_64,i386}:{Debug,Release}`
    - name: make
      run: make --warn-undefined-variables -R -j all        
    - name: make test
      run: make --warn-undefined-variables -R -j -k test || true
    - name: make clean
      run: make --warn-undefined-variables -R -j CLEAN="all git(gsl) all(gsl)" clean
